"""collection streams

Revision ID: 00f6861011dc
Revises: 6baa2929d182
Create Date: 2026-08-05 21:25:18.383639

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '00f6861011dc'
down_revision: str | None = '6baa2929d182'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_streams',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'kind', name='uq_stream_agent_kind')
    )
    op.create_index(op.f('ix_collection_streams_agent_id'), 'collection_streams', ['agent_id'], unique=False)
    op.create_index(op.f('ix_collection_streams_organization_id'), 'collection_streams', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_streams_organization_id'), table_name='collection_streams')
    op.drop_index(op.f('ix_collection_streams_agent_id'), table_name='collection_streams')
    op.drop_table('collection_streams')
    # ### end Alembic commands ###
