"""rule false_positives

Revision ID: 065ebd93f716
Revises: 61025bf62a91
Create Date: 2026-08-05 20:25:16.660289

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '065ebd93f716'
down_revision: str | None = '61025bf62a91'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_rules', sa.Column('false_positives', sa.BigInteger(), nullable=False, server_default='0'))
    op.alter_column('detection_rules', 'false_positives', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection_rules', 'false_positives')
    # ### end Alembic commands ###
