"""notification channels

Revision ID: 0d44144aa21e
Revises: c2181795c7da
Create Date: 2026-08-04 20:32:24.337260

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0d44144aa21e'
down_revision: str | None = 'c2181795c7da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=1024), nullable=False),
    sa.Column('min_severity', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_channels_organization_id'), 'notification_channels', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_channels_organization_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    # ### end Alembic commands ###
