"""logs vulns forensics

Revision ID: 6336701ef368
Revises: 2bf18da9c42f
Create Date: 2026-08-04 15:58:01.054414

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6336701ef368'
down_revision: str | None = '2bf18da9c42f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forensic_snapshots',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('host', sa.String(length=120), nullable=False),
    sa.Column('processes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('connections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forensic_snapshots_host'), 'forensic_snapshots', ['host'], unique=False)
    op.create_index(op.f('ix_forensic_snapshots_organization_id'), 'forensic_snapshots', ['organization_id'], unique=False)
    op.create_table('log_entries',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('host', sa.String(length=120), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_host'), 'log_entries', ['host'], unique=False)
    op.create_index(op.f('ix_log_entries_organization_id'), 'log_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_log_entries_source'), 'log_entries', ['source'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('fix', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_organization_id'), 'vulnerabilities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_severity'), 'vulnerabilities', ['severity'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_target'), 'vulnerabilities', ['target'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_target'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_severity'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_organization_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_log_entries_source'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_organization_id'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_host'), table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_forensic_snapshots_organization_id'), table_name='forensic_snapshots')
    op.drop_index(op.f('ix_forensic_snapshots_host'), table_name='forensic_snapshots')
    op.drop_table('forensic_snapshots')
    # ### end Alembic commands ###
