"""software packages and discovery schedules

Revision ID: 6baa2929d182
Revises: 065ebd93f716
Create Date: 2026-08-05 20:53:18.036382

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6baa2929d182'
down_revision: str | None = '065ebd93f716'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software_packages',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('host', sa.String(length=120), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=False),
    sa.Column('publisher', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_packages_host'), 'software_packages', ['host'], unique=False)
    op.create_index(op.f('ix_software_packages_organization_id'), 'software_packages', ['organization_id'], unique=False)
    op.create_table('discovery_schedules',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('subnet', sa.String(length=64), nullable=False),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_schedules_agent_id'), 'discovery_schedules', ['agent_id'], unique=False)
    op.create_index(op.f('ix_discovery_schedules_next_run_at'), 'discovery_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_discovery_schedules_organization_id'), 'discovery_schedules', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovery_schedules_organization_id'), table_name='discovery_schedules')
    op.drop_index(op.f('ix_discovery_schedules_next_run_at'), table_name='discovery_schedules')
    op.drop_index(op.f('ix_discovery_schedules_agent_id'), table_name='discovery_schedules')
    op.drop_table('discovery_schedules')
    op.drop_index(op.f('ix_software_packages_organization_id'), table_name='software_packages')
    op.drop_index(op.f('ix_software_packages_host'), table_name='software_packages')
    op.drop_table('software_packages')
    # ### end Alembic commands ###
