"""device tags and vuln status

Revision ID: 84801975d836
Revises: 0d44144aa21e
Create Date: 2026-08-04 21:02:24.353401

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '84801975d836'
down_revision: str | None = '0d44144aa21e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('vulnerabilities', sa.Column('status', sa.String(length=16), nullable=False, server_default='open'))
    op.create_index(op.f('ix_vulnerabilities_status'), 'vulnerabilities', ['status'], unique=False)
    # Ondoa server_default baada ya kujaza rows zilizopo, ORM inaweka default yenyewe.
    op.alter_column('devices', 'tags', server_default=None)
    op.alter_column('vulnerabilities', 'status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_status'), table_name='vulnerabilities')
    op.drop_column('vulnerabilities', 'status')
    op.drop_column('devices', 'tags')
    # ### end Alembic commands ###
