"""devices, security_events, sensor_tokens

Revision ID: a85fa1fb02ab
Revises: f2963d39996f
Create Date: 2026-08-04 11:42:30.423739

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a85fa1fb02ab'
down_revision: str | None = 'f2963d39996f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('last_ip', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('discovered', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('events_count', sa.BigInteger(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'mac', name='uq_device_org_mac')
    )
    op.create_index(op.f('ix_devices_last_ip'), 'devices', ['last_ip'], unique=False)
    op.create_index(op.f('ix_devices_mac'), 'devices', ['mac'], unique=False)
    op.create_index(op.f('ix_devices_organization_id'), 'devices', ['organization_id'], unique=False)
    op.create_table('sensor_tokens',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_tokens_organization_id'), 'sensor_tokens', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sensor_tokens_token_hash'), 'sensor_tokens', ['token_hash'], unique=True)
    op.create_table('security_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=True),
    sa.Column('src_mac', sa.String(length=17), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('dst_ip', sa.String(length=45), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('pulse_count', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('asn', sa.Integer(), nullable=True),
    sa.Column('asn_org', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_device_id'), 'security_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_security_events_domain'), 'security_events', ['domain'], unique=False)
    op.create_index(op.f('ix_security_events_dst_ip'), 'security_events', ['dst_ip'], unique=False)
    op.create_index(op.f('ix_security_events_occurred_at'), 'security_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_security_events_organization_id'), 'security_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_events_severity'), 'security_events', ['severity'], unique=False)
    op.create_index(op.f('ix_security_events_verdict'), 'security_events', ['verdict'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_events_verdict'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_severity'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_organization_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_occurred_at'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_dst_ip'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_domain'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_device_id'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_sensor_tokens_token_hash'), table_name='sensor_tokens')
    op.drop_index(op.f('ix_sensor_tokens_organization_id'), table_name='sensor_tokens')
    op.drop_table('sensor_tokens')
    op.drop_index(op.f('ix_devices_organization_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_mac'), table_name='devices')
    op.drop_index(op.f('ix_devices_last_ip'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
